// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xnn_descent.h"

extern XNn_descent_Config XNn_descent_ConfigTable[];

XNn_descent_Config *XNn_descent_LookupConfig(u16 DeviceId) {
	XNn_descent_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XNN_DESCENT_NUM_INSTANCES; Index++) {
		if (XNn_descent_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XNn_descent_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XNn_descent_Initialize(XNn_descent *InstancePtr, u16 DeviceId) {
	XNn_descent_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XNn_descent_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XNn_descent_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

