// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xnn_descent.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XNn_descent_CfgInitialize(XNn_descent *InstancePtr, XNn_descent_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XNn_descent_Start(XNn_descent *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNn_descent_ReadReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_AP_CTRL) & 0x80;
    XNn_descent_WriteReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XNn_descent_IsDone(XNn_descent *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNn_descent_ReadReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XNn_descent_IsIdle(XNn_descent *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNn_descent_ReadReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XNn_descent_IsReady(XNn_descent *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNn_descent_ReadReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XNn_descent_EnableAutoRestart(XNn_descent *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNn_descent_WriteReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XNn_descent_DisableAutoRestart(XNn_descent *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNn_descent_WriteReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_AP_CTRL, 0);
}

void XNn_descent_Set_data_in(XNn_descent *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNn_descent_WriteReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_DATA_IN_DATA, Data);
}

u32 XNn_descent_Get_data_in(XNn_descent *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNn_descent_ReadReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_DATA_IN_DATA);
    return Data;
}

void XNn_descent_Set_rng_state(XNn_descent *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNn_descent_WriteReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_RNG_STATE_DATA, Data);
}

u32 XNn_descent_Get_rng_state(XNn_descent *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNn_descent_ReadReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_RNG_STATE_DATA);
    return Data;
}

void XNn_descent_Set_result_out_index(XNn_descent *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNn_descent_WriteReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_RESULT_OUT_INDEX_DATA, Data);
}

u32 XNn_descent_Get_result_out_index(XNn_descent *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNn_descent_ReadReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_RESULT_OUT_INDEX_DATA);
    return Data;
}

void XNn_descent_Set_result_out_dist(XNn_descent *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNn_descent_WriteReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_RESULT_OUT_DIST_DATA, Data);
}

u32 XNn_descent_Get_result_out_dist(XNn_descent *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNn_descent_ReadReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_RESULT_OUT_DIST_DATA);
    return Data;
}

void XNn_descent_InterruptGlobalEnable(XNn_descent *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNn_descent_WriteReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_GIE, 1);
}

void XNn_descent_InterruptGlobalDisable(XNn_descent *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNn_descent_WriteReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_GIE, 0);
}

void XNn_descent_InterruptEnable(XNn_descent *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XNn_descent_ReadReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_IER);
    XNn_descent_WriteReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_IER, Register | Mask);
}

void XNn_descent_InterruptDisable(XNn_descent *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XNn_descent_ReadReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_IER);
    XNn_descent_WriteReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_IER, Register & (~Mask));
}

void XNn_descent_InterruptClear(XNn_descent *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNn_descent_WriteReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_ISR, Mask);
}

u32 XNn_descent_InterruptGetEnabled(XNn_descent *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XNn_descent_ReadReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_IER);
}

u32 XNn_descent_InterruptGetStatus(XNn_descent *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XNn_descent_ReadReg(InstancePtr->Control_BaseAddress, XNN_DESCENT_CONTROL_ADDR_ISR);
}

