// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// control
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of data_in
//        bit 31~0 - data_in[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of rng_state
//        bit 31~0 - rng_state[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of result_out_index
//        bit 31~0 - result_out_index[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of result_out_dist
//        bit 31~0 - result_out_dist[31:0] (Read/Write)
// 0x2c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XNN_DESCENT_CONTROL_ADDR_AP_CTRL               0x00
#define XNN_DESCENT_CONTROL_ADDR_GIE                   0x04
#define XNN_DESCENT_CONTROL_ADDR_IER                   0x08
#define XNN_DESCENT_CONTROL_ADDR_ISR                   0x0c
#define XNN_DESCENT_CONTROL_ADDR_DATA_IN_DATA          0x10
#define XNN_DESCENT_CONTROL_BITS_DATA_IN_DATA          32
#define XNN_DESCENT_CONTROL_ADDR_RNG_STATE_DATA        0x18
#define XNN_DESCENT_CONTROL_BITS_RNG_STATE_DATA        32
#define XNN_DESCENT_CONTROL_ADDR_RESULT_OUT_INDEX_DATA 0x20
#define XNN_DESCENT_CONTROL_BITS_RESULT_OUT_INDEX_DATA 32
#define XNN_DESCENT_CONTROL_ADDR_RESULT_OUT_DIST_DATA  0x28
#define XNN_DESCENT_CONTROL_BITS_RESULT_OUT_DIST_DATA  32

